version: '3.3'
services:
  solr:
    image: "solr:7.3.1"
    ports:
     - "8983:8983"
    # volumes:
      # - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
  nutch:
    image: "apache/nutch:release-1.16"
    links:
      - solr
    environment: 
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    working_dir: /root/nutch
    command: '/root/nutch/bin/crawl -i -D solr.server.url=http://solr:8983/solr/mycore -s urls crawl 10'
    volumes:
        - ./nutch/conf/index-writers.xml:/root/nutch/conf/index-writers.xml
        - ./nutch/conf/nutch-site.xml:/root/nutch/conf/nutch-site.xml
        - ./nutch/conf/regex-urlfilter.txt:/root/nutch/conf/regex-urlfilter.txt
        - ./nutch/urls/seed.txt:/root/nutch/urls/seed.txt
# volumes:
#   data: